swagger: '2.0'
info:
  description: >-
    This is the API documentation.
  version: 1.0.0
  title: API - Documentation
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: data
    description: Operations about data
schemes:
  - http
paths:
  /data:
    get:
      tags:
        - data
      summary: Get data
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: Return data
          schema:
            type: object
            properties:
              data:
                type: number
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Sector:
    type: object
    properties:
      _id:
        type: string
      name:
        type: string
      deleted:
        type: boolean
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
